name: PR Approval Reminder
on:
  schedule:
    # Executa a cada 5 minutos
    - cron: '*/1 * * * *'

jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:
      # Configurar GitHub CLI com token
      - name: Configurar GitHub CLI
        run: echo "${{ secrets.GT_TOKEN }}" | gh auth login --with-token

      # Buscar PRs abertas
      - name: Buscar PRs abertas
        run: |
          gh pr list --state open --json title,reviewDecision,reviews,merged --jq '.' > prs_abertas.json
          cat prs_abertas.json

      # Enviar lembretes para Google Chat
      - name: Enviar Lembretes para Google Chat
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          if [ -s prs_abertas.json ]; then
            cat prs_abertas.json | jq -c '.[]' | while read -r pr; do
              title=$(echo $pr | jq -r '.title')
              reviewDecision=$(echo $pr | jq -r '.reviewDecision')
              reviews=$(echo $pr | jq -r '.reviews | length')
              merged=$(echo $pr | jq -r '.merged')

              # Verifica PR sem nenhuma aprovação
              if [[ $reviews -eq 0 ]]; then
                curl -X POST -H "Content-Type: application/json" \
                -d "{\"text\":\"PR aberta sem revisões: $title\"}" $WEBHOOK_URL

              # Verifica PR com menos de 2 revisores
              elif [[ $reviews -lt 2 ]] && [[ $reviewDecision != "APPROVED" ]]; then
                curl -X POST -H "Content-Type: application/json" \
                -d "{\"text\":\"PR $title está aguardando revisões (apenas $reviews revisores até agora).\"}" $WEBHOOK_URL

              # Verifica PR com duas aprovações, mas sem merge
              elif [[ $reviewDecision == "APPROVED" ]] && [[ $merged == "false" ]]; then
                curl -X POST -H "Content-Type: application/json" \
                -d "{\"text\":\"PR aprovada, mas ainda não foi mergeada: $title\"}" $WEBHOOK_URL

              # Verifica PR onde mudanças foram solicitadas
              elif [[ $reviewDecision == "CHANGES_REQUESTED" ]]; then
                curl -X POST -H "Content-Type: application/json" \
                -d "{\"text\":\"PR $title está aguardando alterações solicitadas pelos revisores.\"}" $WEBHOOK_URL
              fi
            done
          fi
