name: PR Approval Reminder
on:
  workflow_dispatch:

jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Checar o repositório
        uses: actions/checkout@v3 
        
      - name: Configurar GitHub CLI
        run: gh auth login --with-token ${{ secrets.GT_TOKEN }}
        
      - name: Buscar PRs abertas
        run: |
          gh pr list --state open --json number,title,reviewDecision,reviews > prs_abertas.json
          echo "PRs abertas salvas em prs_abertas.json"
      - name: Verificar e Enviar Lembretes
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          # Verifica se o arquivo está vazio
          if [ ! -s prs_abertas.json ]; then
            echo "Nenhuma PR aberta encontrada."
            exit 0
          fi
          # Processa o arquivo JSON
          cat prs_abertas.json | jq -c '.[] | select(.reviewDecision != "APPROVED")' | while read -r pr; do
            PR_TITLE=$(echo $pr | jq -r '.title')
            if [ -n "$WEBHOOK_URL" ]; then
              curl -X POST -H "Content-Type: application/json" \
                -d "{\"text\":\"PR aberta sem aprovação: $PR_TITLE\"}" $WEBHOOK_URL
            else
