- name: Enviar Lembretes para Google Chat
  env:
    WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
  run: |
    if [ -s prs_abertas.json ]; then
      cat prs_abertas.json | jq -r '.[]' | while read -r pr; do
        if [[ $(echo $pr | jq -r '.requestedReviewers | length') -eq 0 ]]; then
          # PR aberta sem revisores aprovando no chat
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"text\":\"PR aberta sem revisores aprovando: $(echo $pr | jq -r '.title')\"}" \
          $WEBHOOK_URL
        elif [[ $(echo $pr | jq -r '.reviewDecision') != "APPROVED" ]]; then
          # PR aberta sem duas aprovações no chat
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"text\":\"PR aberta sem duas aprovações: $(echo $pr | jq -r '.title')\"}" \
          $WEBHOOK_URL
        elif [[ $(echo $pr | jq -r '.reviewDecision') == "APPROVED" ]] && [[ $(echo $pr | jq -r '.requestedReviewers | length') -eq 2 ]]; then
          # PR aprovada, mas no chat não tem ícone igual a "marca de seleção"
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"text\":\"PR aprovada, mas precisa verificar se foi merge: $(echo $pr | jq -r '.title')\"}" \
          $WEBHOOK_URL
        elif [[ $(echo $pr | jq -r '.merged') == "false" ]]; then
          # PR aberta sem estar mergeada
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"text\":\"PR aberta sem merge: $(echo $pr | jq -r '.title')\"}" \
          $WEBHOOK_URL
        fi
      done
    fi
