name: PR Approval Reminder
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Checar o repositório
        uses: actions/checkout@v3 # Clona o repositório para o ambiente

      - name: Configurar GitHub CLI
        run: gh auth login --with-token ${{ secrets.GT_TOKEN }}

      - name: Buscar PRs abertas
        run: |
          # Lista todas as PRs abertas
          gh pr list --state open --json number,title,reviewDecision,reviews > prs_abertas.json
          cat prs_abertas.json

      - name: Enviar Lembretes para Google Chat
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          # Verifica se há PRs abertas
          if [ -s prs_abertas.json ]; then
            cat prs_abertas.json | jq -r '.[] | select(.reviewDecision != "APPROVED")' | while read -r pr; do
              curl -X POST -H "Content-Type: application/json" \
                -d "{\"text\":\"PR aberta sem aprovação: $(echo $pr | jq -r '.title')\"}" $WEBHOOK_URL
            done
          fi
