name: testar secrets
on:
  schedule:
    # Executa a cada minuto
    - cron: '*/1 * * * *'
  workflow_dispatch: # Habilita execução manual

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Testar acesso aos secrets
        run: |
          if [ -z "${{ secrets.GT_TOKEN }}" ]; then
            echo "GT_TOKEN não está configurado!"
            exit 1
          else
            echo "GT_TOKEN encontrado com sucesso!"
          fi
